[project]
name = "pihmmi"
version = "1.6.0"
description = "Library for protein sequence analysis and distant ortholog search"
authors = [
    {name = "Maksim Liukshin 247034@vut.cz"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "orthodb @ git+https://gitlab.com/ezlab/orthodb_py.git",
    "pyhmmer (>=0.11.1,<0.12.0)",
    "biopython (>=1.85,<2.0)",
    "numpy (>=2.3.2,<3.0.0)",
    "pandas (>=2.3.1,<3.0.0)",
    "matplotlib (>=3.10.3,<4.0.0)",
    "scipy (>=1.16.1,<2.0.0)",
    "requests (>=2.32.4,<3.0.0)",
    "scikit-learn (>=1.7.1,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
